### ISSUE TITLE
Cat UI 1.4 For Angel（免费版） - 折影轻梦

### ISSUE THREAD

**Issue by nexmoe** [nexmoe/nexmoe.github.io#18]
https://nexmoe.com/1111.html 

 Waiting for the people who is angel to me.

**Comment by Kosthi** [comment]
大佬，请问这个主题怎么用，hexo好像并不支持php

**Comment by nexmoe** [comment]
> @JokerMas
> 大佬，请问这个主题怎么用，hexo好像并不支持php

这个是 typecho 的主题

**Comment by sonicbaka** [comment]
这么好看的主题博主选择开源 大爱！
