### ISSUE TITLE
Hexo 主题 Nexmoe - 折影轻梦

### ISSUE THREAD

**Issue by nexmoe** [nexmoe/nexmoe.github.io#23]
https://nexmoe.com/hexo-theme-nexmoe.html 

 一个比较特别的 Hexo 主题

**Comment by AHCorn** [comment]
ohhh　太巧了..刚好想起问过大佬这个主题什么时候发布，一过来就碰到了

**Comment by nexmoe** [comment]
> @lolicorncom
> ohhh　太巧了..刚好想起问过大佬这个主题什么时候发布，一过来就碰到了

大概月底或者8月初发布的样子

**Comment by AHCorn** [comment]
> @nexmoe
> > @lolicorncom
> > ohhh　太巧了..刚好想起问过大佬这个主题什么时候发布，一过来就碰到了
> 
> 大概月底或者8月初发布的样子

请问大佬catui的使用说明还有嘛，最近用了回来发现您把使用说明删掉惹

**Comment by nexmoe** [comment]
> @lolicorncom
> > @nexmoe
> > > @lolicorncom
> > > ohhh　太巧了..刚好想起问过大佬这个主题什么时候发布，一过来就碰到了
> > 
> > 大概月底或者8月初发布的样子
> 
> 请问大佬catui的使用说明还有嘛，最近用了回来发现您把使用说明删掉惹

等我放假把 Typecho 复活

**Comment by AHCorn** [comment]
> @nexmoe
> > @lolicorncom
> > > @nexmoe
> > > > @lolicorncom
> > > > ohhh　太巧了..刚好想起问过大佬这个主题什么时候发布，一过来就碰到了
> > > 
> > > 大概月底或者8月初发布的样子
> > 
> > 请问大佬catui的使用说明还有嘛，最近用了回来发现您把使用说明删掉惹
> 
> 等我放假把 Typecho 复活

好的 谢谢

**Comment by OrientalFantasy** [comment]
啊嘞，你的头像怎么那么眼熟...等等，是剑圣莱茵哈鲁特·范·阿斯特雷亚！？

**Comment by nexmoe** [comment]
> @OrientalFantasy
> 啊嘞，你的头像怎么那么眼熟...等等，是剑圣莱茵哈鲁特·范·阿斯特雷亚！？

对啊
