### ISSUE TITLE
朋友 - 折影轻梦

### ISSUE THREAD

**Issue by nexmoe** [nexmoe/nexmoe.github.io#4]
https://nexmoe.github.io/PY.html 

 情怀我们会慢慢长大成人，随着季节的不停变换路边盛开的鲜花也在不断变化，那个季节盛开的鲜花到底叫什么名字，轻轻摇曳着一旦触摸它就会轻轻地被扎到，用鼻子靠近闻一闻，会有一股淡淡的青涩太阳的芳香，随着那股香味慢慢变淡我们也在长大成人，但是那朵花一定会在某处继续盛开。 友情链接

**Comment by w4ctech** [comment]
这个blog theme超好看

**Comment by zhoulianglen** [comment]
想和贵博客交换一下友情链接，我这边已经添加好了，地址在：https://blog.eric.ec/
感谢～

**Comment by nexmoe** [comment]
暂时不换友联……
