### ISSUE TITLE
关于 - 折影轻梦

### ISSUE THREAD

**Issue by nexmoe** [nexmoe/nexmoe.github.io#5]
https://nexmoe.com/about.html 

 我，一个农历属蛇，公历生于一月的男孩子。 关于我人格我的人格分为善与恶，以下 折影轻梦：崇尚自由、热爱技术、十分乐观。奈西萌：由 Nexmoe 直译而来，喜欢漂亮的妹子、帅气的妹纸、漂亮的男孩子、帅气的男孩子、各种艺术品、喜欢小动物、喜欢萌的东西。 黑：易怒、报复心强、自闭、阴暗、无法控制好自己。简：孤僻、社交恐惧症、对喜欢的东西不敢追求、胆小而懦弱。 七宗罪我的缺点：傲慢、妒忌、暴怒、懒惰、贪婪

**Comment by Mashiro2000** [comment]
给dalao拜年了(=・ω・=)

**Comment by Kosthi** [comment]
主題鏈接失效了

**Comment by nexmoe** [comment]
> @JokerMas
> 主題鏈接失效了

啥

**Comment by Kosthi** [comment]
> > @JokerMas
> > 主題鏈接失效了
> 
> 啥
你的博客主題是什麼？

**Comment by nexmoe** [comment]
> @JokerMas
> > > @JokerMas
> > > 主題鏈接失效了
> > 
> > 啥
> 你的博客主題是什麼？
> 

自己写的还没完工

**Comment by nexmoe** [comment]
> @JokerMas
> > > @JokerMas
> > > 主題鏈接失效了
> > 
> > 啥
> 你的博客主題是什麼？
> 

自己写的还没完工

**Comment by JokerMas** [comment]
> @nexmoe
> > @JokerMas
> > > > @JokerMas
> > > > 主題鏈接失效了
> > > 
> > > 啥
> > 你的博客主題是什麼？
> > 
> 
> 自己写的还没完工

> @nexmoe
> > @JokerMas
> > > > @JokerMas
> > > > 主題鏈接失效了
> > > 
> > > 啥
> > 你的博客主題是什麼？
> > 
> 
> 自己写的还没完工
能分享嗎？

**Comment by Kosthi** [comment]
> 自己写的还没完工
能分享嗎？

**Comment by ghost** [comment]
> @JokerMas
> > 自己写的还没完工
> 能分享嗎？
> 


> @JokerMas
> > 自己写的还没完工
> 能分享嗎？
> 

同求同求！

**Comment by prcups** [comment]
你好，我是和你差不多大的一名男生，很高兴能看到你的博客！我的博客地址：http://thisworld.site （我没想交换友链）。我比较喜欢写诗，虽然写得不怎么样。现在博客因为高三停更了，高考完会好好整整，希望自己能写个主题出来。

**Comment by ltsj** [comment]
饥荒1000天倒不是很难 就是有点无聊233

**Comment by nexmoe** [comment]
> @ltsj
> 饥荒1000天倒不是很难 就是有点无聊233

所以饥荒1000天是需要一群小伙伴一起玩才有趣的

**Comment by nexmoe** [comment]
> @Parkmimi
> > @JokerMas
> > > 自己写的还没完工
> > 能分享嗎？
> > 
> 
> 
> > @JokerMas
> > > 自己写的还没完工
> > 能分享嗎？
> > 
> 
> 同求同求！

已开源
